apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-reference-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
          image: golang-reference-api:latest
          env:
            - name: APP_ENVIRONMENT
              value: localdev
      nodeSelector:
      volumes:
      serviceAccountName:
