version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0

parameters:
  workspace_directory:
    type: string
    default: "/home/circleci/app"
  dev-changed:
    type: boolean
    default: false
  sta-changed:
    type: boolean
    default: false
  api-changed:
    type: boolean
    default: false

executors:
  spectral-executor:
    docker:
      - image: bitnami/git:latest
    working_directory: << pipeline.parameters.workspace_directory >>

jobs:
  api-spec-lint:
    executor: spectral-executor
    steps:
      - checkout
      - run:
          name: "Checkout Monaco Spectral Ruleset"
          command: git clone "git@github.com:monacohq/api-standards-linter.git" --branch "main" ./spectral
      - run: "[ -d lint-results ] || mkdir lint-results"
      - run:
          name: "Install Spectral"
          command: curl -L https://raw.github.com/stoplightio/spectral/master/scripts/install.sh | sh
      - run:
          name: "Run Spectral Lint"
          command: /usr/local/bin/spectral lint -r ./spectral/monaco.yml -o lint-results/golang-reference-api.xml -f junit internal/docs/swagger.json
      - store_test_results:
          path: lint-results

  deploy-api-kustomize:
    docker:
      - image: cimg/base:stable
    parameters:
      kustomize-folder:
        description: kustomize folder to deploy, for example adev-app-main
        type: string
      kubectl-version:
        type: string
        description: kubectl version
        default: "latest"
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          aws-region: ${AWS_REGION}
          cluster-name: ${EKS_CLUSTER_NAME}
          install-kubectl: true
          kubectl-version: << parameters.kubectl-version >>
      - run:
          name: Apply kustomization
          command: |
            kubectl kustomize deploy/<< parameters.kustomize-folder >> | kubectl -n $EKS_NAMESPACE apply -f -

workflows:
  api-spec-lint:
    when: << pipeline.parameters.api-changed >>
    jobs:
      - api-spec-lint

  deploy-api-dev:
    when: << pipeline.parameters.dev-changed >>
    jobs:
      - deploy-api-kustomize:
          context: golang-reference-api-dev
          kustomize-folder: adev-app-main
          filters:
            tags:
              only: /.*/

  deploy-api-staging:
    when: << pipeline.parameters.sta-changed >>
    jobs:
      - deploy-api-kustomize:
          context: golang-reference-api-staging
          kustomize-folder: asta-app-main
          filters:
            branches:
              only:
                - main
            tags:
              only: /.*/
