resources:
- ../base

namespace: stg-monaco

nameSuffix: "-staging"

commonLabels:
  app.kubernetes.io/name: golang-reference-api
  app.kubernetes.io/version: staging

images:
- name: 3onaco/golang-reference-api
  newName: 929151461716.dkr.ecr.ap-southeast-1.amazonaws.com/app-golang-reference-api
  newTag: v2022.06.30.2212

patchesStrategicMerge:
- deployment-config.yaml
