application:
  port: 8000
  prettylog: false
  url:
    host: "localhost:8000"
    schemes: ["https"]
  timeouts:
    readTimeout: "2s"      
    readHeaderTimeout: "1s"
    writeTimeout: "2s"     
    idleTimeout: "1m"
grpc:
  port: 9000
observability:
  collector:
    host: "otel-collector.opentelemetry-collector"
    port: 4317