resources:
- ../base

namespace: dev-monaco

nameSuffix: "-dev"

commonLabels:
  app.kubernetes.io/name: golang-reference-api
  app.kubernetes.io/version: dev

images:
- name: 3onaco/golang-reference-api
  newName: 929151461716.dkr.ecr.ap-southeast-1.amazonaws.com/app-golang-reference-api
  newTag: v2022.07.15.1050

patchesStrategicMerge:
- deployment-config.yaml