// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Vincent",
            "email": "vincent.serpoul@crypto.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/payment-plans": {
            "get": {
                "description": "returns pagination of one user's payment plans",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment_plan"
                ],
                "summary": "Renders a user's payment plans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "X-CRYPTO-USER-UUID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Start index in the list",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 10,
                        "minimum": 0,
                        "type": "integer",
                        "description": "Number of items displayed",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Order by payment.created_at asc  OR desc",
                        "name": "created_at_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userfacing.PaymentPlanResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/payment-plans/{uuid}/complete": {
            "post": {
                "description": "completes a payment plan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment_plan"
                ],
                "summary": "Completes a payment plan",
                "parameters": [
                    {
                        "description": "Complete payment plan reqBody",
                        "name": "complete_payment_plan_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internalfacing.CompletePaymentPlanRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Payment Plan UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internalfacing.CompletePaymentPlanResponse"
                        }
                    },
                    "400": {
                        "description": "bad reqBody",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "payment plan not belongs to user",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "payment plan is not in pending",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "payment plan not found",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/payment_plans": {
            "post": {
                "description": "pre creates a payment plan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment_plan"
                ],
                "summary": "Creates a pending a payment plan",
                "parameters": [
                    {
                        "description": "Pre create payment plan reqBody",
                        "name": "pre_create_payment_plan_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internalfacing.CreatePendingPaymentPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internalfacing.CreatePendingPaymentPlanResponse"
                        }
                    },
                    "400": {
                        "description": "bad reqBody",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/handlerwrap.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlerwrap.ErrorResponse": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string"
                },
                "error_msg": {
                    "type": "string"
                }
            }
        },
        "internalfacing.CompletePaymentPlanRequest": {
            "type": "object",
            "properties": {
                "payment": {
                    "$ref": "#/definitions/service.CompletePaymentPlanParams"
                }
            }
        },
        "internalfacing.CompletePaymentPlanResponse": {
            "type": "object",
            "properties": {
                "payment": {
                    "$ref": "#/definitions/service.PaymentPlans"
                }
            }
        },
        "internalfacing.CreatePendingPaymentPlanRequest": {
            "type": "object",
            "properties": {
                "payment": {
                    "$ref": "#/definitions/service.CreatePaymentPlanParams"
                }
            }
        },
        "internalfacing.CreatePendingPaymentPlanResponse": {
            "type": "object",
            "properties": {
                "payment": {
                    "$ref": "#/definitions/service.PaymentPlans"
                }
            }
        },
        "service.CompletePaymentPlanParams": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "service.CreatePaymentPlanParams": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "installments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.PaymentPlanInstallmentParams"
                    }
                },
                "total_amount": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "service.PaymentPlanInstallment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "due_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.PaymentPlanInstallmentParams": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "due_at": {
                    "type": "string"
                }
            }
        },
        "service.PaymentPlans": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "installments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.PaymentPlanInstallment"
                    }
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "userfacing.PaymentPlanResponse": {
            "type": "object",
            "properties": {
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.PaymentPlans"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "bnpl API",
	Description:      "This is the service used for buy now pay later.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
