// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePaymentInstallments(ctx context.Context, arg *CreatePaymentInstallmentsParams) (*CreatePaymentInstallmentsRow, error)
	CreatePaymentPlan(ctx context.Context, arg *CreatePaymentPlanParams) (*CreatePaymentPlanRow, error)
	ListPaymentInstallmentsByPlanID(ctx context.Context, paymentPlanID uuid.UUID) ([]*ListPaymentInstallmentsByPlanIDRow, error)
	ListPaymentPlansByUserID(ctx context.Context, userID uuid.UUID) ([]*ListPaymentPlansByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
