application:
  version: "v1"
  port: 8000
  prettylog: false
  url:
    host: "localhost:8000"
    schemes: ["https"]
  timeouts:
    readTimeout: "2s"      
    readHeaderTimeout: "1s"
    writeTimeout: "2s"     
    idleTimeout: "1m"
grpc:
  port: 9000
observability:
  collector:
    host: "opentelemetry-collector.otel-collector"
    port: 4317
db:
  host: "mypostgres.postgres"
  port: 5432
  user: "golang_reference_api_app"
  password: "password"
  database: "golang_reference_api_local"
  maxConns: 10
  maxIdleConns: 10
  maxLifeTime: "1m"